apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres-database
  description: PostgreSQL database for Backstage catalog
  tags:
    - postgresql
    - database
spec:
  type: database
  owner: platform-admins
  system: developer-portal
