apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-api
  description: Secure payment processing API
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: dokaseca/payment-api
  tags:
    - java
    - rest-api
    - pci-compliant
  links:
    - url: https://api.dokaseca.local/payments
      title: API Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: developers
  system: payment-processing
  dependsOn:
    - resource:payment-database
  providesApis:
    - payment-api
